const PICTURES_COLLECTION = 'pictures';
const MESSAGES_COLLECTION = 'messages';
const MEMORIES_COLLECTION = 'memories';

export { 
    PICTURES_COLLECTION,
    MESSAGES_COLLECTION,
    MEMORIES_COLLECTION,
}